//! Gemini background analyst — watches K8s event stream and generates
//! proactive insights. Runs as a separate tokio task, pushing insights
//! to the TUI via an mpsc channel.
//!
//! Architecture:
//!   Go agent streams events via gRPC → Rust collects a rolling window →
//!   Every N seconds, sends the window to Gemini API → Gemini returns
//!   insights → Pushed to TUI as system messages.

use anyhow::Result;
use serde_json::{json, Value};
use std::collections::VecDeque;
use std::sync::Arc;
use tokio::sync::{mpsc, Mutex};
use tokio::time::{interval, Duration};

use crate::agent::AgentClient;

const GEMINI_API_URL: &str = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent";
const ANALYSIS_INTERVAL_SECS: u64 = 30;
const EVENT_WINDOW_SIZE: usize = 100;

/// A proactive insight generated by Gemini.
#[derive(Clone, Debug)]
pub struct GeminiInsight {
    pub severity: InsightSeverity,
    pub message: String,
    pub timestamp: String,
}

#[derive(Clone, Debug)]
pub enum InsightSeverity {
    Info,
    Warning,
    Critical,
}

/// Spawns the Gemini background analyst as a tokio task.
/// Returns a receiver for insights that the TUI can consume.
pub fn spawn_gemini_analyst(
    agent: AgentClient,
    gemini_api_key: String,
) -> mpsc::Receiver<GeminiInsight> {
    let (tx, rx) = mpsc::channel::<GeminiInsight>(32);

    tokio::spawn(async move {
        if let Err(e) = run_analyst(agent, &gemini_api_key, tx).await {
            tracing::error!("Gemini analyst task failed: {}", e);
        }
    });

    rx
}

async fn run_analyst(
    mut agent: AgentClient,
    api_key: &str,
    tx: mpsc::Sender<GeminiInsight>,
) -> Result<()> {
    let http = reqwest::Client::new();
    let event_buffer: Arc<Mutex<VecDeque<String>>> =
        Arc::new(Mutex::new(VecDeque::with_capacity(EVENT_WINDOW_SIZE)));

    let mut tick = interval(Duration::from_secs(ANALYSIS_INTERVAL_SECS));

    loop {
        tick.tick().await;

        // Collect recent events from the cluster
        let events_text = match agent.get_events("", "", 30).await {
            Ok(text) => text,
            Err(e) => {
                tracing::warn!("Gemini analyst: failed to fetch events: {}", e);
                continue;
            }
        };

        // Also get a quick pod overview for context
        let pods_text = match agent.get_pods("", "").await {
            Ok(text) => text,
            Err(_) => String::new(),
        };

        // Update rolling buffer
        {
            let mut buffer = event_buffer.lock().await;
            buffer.push_back(events_text.clone());
            while buffer.len() > EVENT_WINDOW_SIZE {
                buffer.pop_front();
            }
        }

        // Send to Gemini for analysis
        let prompt = format!(
            "{}\n\nCurrent cluster events:\n{}\n\nCurrent pod status:\n{}\n",
            GEMINI_SYSTEM_PROMPT, events_text, pods_text
        );

        match call_gemini(&http, api_key, &prompt).await {
            Ok(analysis) => {
                // Parse Gemini's response into insights
                let insights = parse_insights(&analysis);
                for insight in insights {
                    if tx.send(insight).await.is_err() {
                        tracing::info!("Gemini analyst: TUI receiver dropped, stopping");
                        return Ok(());
                    }
                }
            }
            Err(e) => {
                tracing::warn!("Gemini API call failed: {}", e);
            }
        }
    }
}

async fn call_gemini(
    http: &reqwest::Client,
    api_key: &str,
    prompt: &str,
) -> Result<String> {
    let url = format!("{}?key={}", GEMINI_API_URL, api_key);

    let body = json!({
        "contents": [{
            "parts": [{
                "text": prompt
            }]
        }],
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 512,
        }
    });

    let resp = http
        .post(&url)
        .header("content-type", "application/json")
        .json(&body)
        .send()
        .await?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await?;
        return Err(anyhow::anyhow!("Gemini API error {}: {}", status, body));
    }

    let json: Value = resp.json().await?;

    // Extract text from Gemini response
    let text = json["candidates"][0]["content"]["parts"][0]["text"]
        .as_str()
        .unwrap_or("")
        .to_string();

    Ok(text)
}

/// Parse Gemini's response into structured insights.
/// Gemini is prompted to return one insight per line with a severity prefix.
fn parse_insights(raw: &str) -> Vec<GeminiInsight> {
    let timestamp = chrono::Local::now().format("%H:%M:%S").to_string();
    let mut insights = Vec::new();

    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("ALL_CLEAR") {
            continue;
        }

        let (severity, message) = if line.starts_with("CRITICAL:") {
            (InsightSeverity::Critical, line.trim_start_matches("CRITICAL:").trim())
        } else if line.starts_with("WARNING:") {
            (InsightSeverity::Warning, line.trim_start_matches("WARNING:").trim())
        } else if line.starts_with("INFO:") {
            (InsightSeverity::Info, line.trim_start_matches("INFO:").trim())
        } else {
            continue; // Skip lines that don't match the expected format
        };

        insights.push(GeminiInsight {
            severity,
            message: message.to_string(),
            timestamp: timestamp.clone(),
        });
    }

    insights
}

const GEMINI_SYSTEM_PROMPT: &str = r#"You are a Kubernetes cluster monitoring analyst. You receive periodic snapshots of cluster events and pod status. Your job is to identify patterns, anomalies, and actionable insights that a developer should know about.

Rules:
- Only report NEW or WORSENING conditions, not stable/healthy state
- If everything looks normal, respond with just: ALL_CLEAR
- Each insight must be on its own line with a severity prefix
- Keep each insight to one concise sentence
- Focus on patterns (repeated failures, escalating restarts, resource pressure)

Format each insight as:
CRITICAL: <message>  — for active outages, data loss risk, or cascading failures
WARNING: <message>   — for degraded performance, approaching limits, or recurring errors
INFO: <message>      — for notable changes, completed operations, or optimization opportunities

Examples:
CRITICAL: redis-master-0 has OOMKilled 5 times in 15 minutes — memory limit 256Mi is insufficient
WARNING: api-gateway pod restarts trending up: 3 restarts in last 10 minutes
INFO: nginx-web deployment scaled from 3 to 5 replicas — CPU usage was 78%"#;
